//! Flow project initialization
//!
//! Scaffolds a new `cycles.toml` and `.flow/` directory for projects
//! that are new to Flow.

use anyhow::{bail, Context, Result};
use std::path::Path;

/// The default cycles.toml template for new projects.
///
/// Includes coding and gardening cycles with reasonable default permissions.
pub const CYCLES_TOML_TEMPLATE: &str = r#"# Flow - Automated Coding Pipeline
# Generated by `flow init`. Customize to fit your project.

[global]
permissions = ["Read", "Glob", "Bash(git log *)", "Bash(git diff *)"]
circuit_breaker_repeated = 5
max_permission_denials = 10
max_consecutive_failures = 3

[[cycle]]
name = "coding"
description = "Pick a task from TODO.md and implement it with TDD"
prompt = """
You are Flow's coding cycle. Follow the /coding-iteration skill workflow.

Pick the highest-priority uncompleted task from TODO.md, implement it with TDD
(RED→GREEN→REFACTOR), run all tests and linting, then commit.
"""
permissions = [
  "Edit(./src/**)",
  "Edit(./tests/**)",
  "Edit(./TODO.md)",
  "Bash(cargo *)",
]
after = []
context = "summaries"
min_interval = 1

[[cycle]]
name = "gardening"
description = "Maintain and improve the codebase"
prompt = """
You are Flow's gardening cycle. Maintain the codebase:
- Update dependencies (cargo update, cargo outdated)
- Remove dead code and unused imports
- Improve test coverage for under-tested modules
- Fix clippy warnings and formatting issues
- Update documentation
"""
permissions = [
  "Edit(./Cargo.toml)",
  "Edit(./Cargo.lock)",
  "Edit(./src/**)",
  "Edit(./tests/**)",
  "Bash(cargo *)",
]
after = ["coding"]
context = "summaries"
min_interval = 3
"#;

/// Initialize a new Flow project in the given directory.
///
/// Creates `cycles.toml` with a default template and the `.flow/` directory.
/// Returns an error if `cycles.toml` already exists (does not overwrite).
///
/// # Errors
/// - `cycles.toml` already exists in the target directory
/// - Cannot create `.flow/` directory
/// - Cannot write `cycles.toml`
pub fn init(project_dir: &Path) -> Result<()> {
    let config_path = project_dir.join("cycles.toml");
    let flow_dir = project_dir.join(".flow");

    if config_path.exists() {
        bail!(
            "cycles.toml already exists at '{}'. \
             Remove it or edit it manually.",
            config_path.display()
        );
    }

    // Create .flow/ directory
    std::fs::create_dir_all(&flow_dir).with_context(|| {
        format!(
            "Failed to create .flow/ directory at '{}'",
            flow_dir.display()
        )
    })?;

    // Write cycles.toml template
    std::fs::write(&config_path, CYCLES_TOML_TEMPLATE)
        .with_context(|| format!("Failed to write cycles.toml at '{}'", config_path.display()))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_init_creates_cycles_toml() {
        let dir = TempDir::new().unwrap();
        init(dir.path()).unwrap();
        assert!(dir.path().join("cycles.toml").exists());
    }

    #[test]
    fn test_init_creates_flow_directory() {
        let dir = TempDir::new().unwrap();
        init(dir.path()).unwrap();
        assert!(dir.path().join(".flow").exists());
        assert!(dir.path().join(".flow").is_dir());
    }

    #[test]
    fn test_init_cycles_toml_contains_coding_cycle() {
        let dir = TempDir::new().unwrap();
        init(dir.path()).unwrap();
        let content = std::fs::read_to_string(dir.path().join("cycles.toml")).unwrap();
        assert!(
            content.contains("name = \"coding\""),
            "Missing coding cycle"
        );
    }

    #[test]
    fn test_init_cycles_toml_contains_gardening_cycle() {
        let dir = TempDir::new().unwrap();
        init(dir.path()).unwrap();
        let content = std::fs::read_to_string(dir.path().join("cycles.toml")).unwrap();
        assert!(
            content.contains("name = \"gardening\""),
            "Missing gardening cycle"
        );
    }

    #[test]
    fn test_init_fails_if_cycles_toml_already_exists() {
        let dir = TempDir::new().unwrap();
        // Create cycles.toml first
        std::fs::write(dir.path().join("cycles.toml"), "existing content").unwrap();
        let result = init(dir.path());
        assert!(result.is_err(), "Should fail if cycles.toml exists");
    }

    #[test]
    fn test_init_error_message_mentions_existing_file() {
        let dir = TempDir::new().unwrap();
        std::fs::write(dir.path().join("cycles.toml"), "existing").unwrap();
        let err = init(dir.path()).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("cycles.toml") && msg.contains("already exists"),
            "Error should mention the existing file: {msg}"
        );
    }

    #[test]
    fn test_init_idempotent_flow_dir_if_exists() {
        let dir = TempDir::new().unwrap();
        // Pre-create .flow/
        std::fs::create_dir_all(dir.path().join(".flow")).unwrap();
        // init should succeed even with .flow/ present
        init(dir.path()).unwrap();
        assert!(dir.path().join("cycles.toml").exists());
    }

    #[test]
    fn test_template_is_valid_toml() {
        // Verify the embedded template can be parsed by FlowConfig
        use crate::cycle::config::FlowConfig;
        FlowConfig::parse(CYCLES_TOML_TEMPLATE).expect("Template must be valid TOML");
    }

    #[test]
    fn test_template_coding_cycle_has_permissions() {
        use crate::cycle::config::FlowConfig;
        let config = FlowConfig::parse(CYCLES_TOML_TEMPLATE).unwrap();
        let coding = config.get_cycle("coding").unwrap();
        assert!(
            !coding.permissions.is_empty(),
            "coding cycle should have permissions"
        );
    }

    #[test]
    fn test_template_gardening_triggers_after_coding() {
        use crate::cycle::config::FlowConfig;
        let config = FlowConfig::parse(CYCLES_TOML_TEMPLATE).unwrap();
        let gardening = config.get_cycle("gardening").unwrap();
        assert!(
            gardening.after.contains(&"coding".to_string()),
            "gardening should trigger after coding"
        );
    }
}
